-- Adds realtime campaign chat table with member-scoped RLS policies.
-- Safe to run multiple times.

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  campaign_id text not null,
  author_user_id uuid not null references auth.users(id) on delete cascade,
  recipient_user_id uuid references auth.users(id) on delete set null,
  author_display text not null default '',
  body text not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint chat_messages_no_self_dm check (
    recipient_user_id is null or recipient_user_id <> author_user_id
  ),
  constraint chat_messages_author_display_len check (char_length(author_display) <= 60),
  constraint chat_messages_body_len check (char_length(btrim(body)) between 1 and 1000)
);

alter table public.chat_messages
  add column if not exists recipient_user_id uuid references auth.users(id) on delete set null;

alter table public.chat_messages
  drop constraint if exists chat_messages_no_self_dm;

alter table public.chat_messages
  add constraint chat_messages_no_self_dm
  check (recipient_user_id is null or recipient_user_id <> author_user_id);

create index if not exists chat_messages_campaign_created_idx
  on public.chat_messages (campaign_id, created_at desc);

create index if not exists chat_messages_campaign_recipient_created_idx
  on public.chat_messages (campaign_id, recipient_user_id, created_at desc);

grant select, insert on public.chat_messages to authenticated;

create or replace function public.list_campaign_member_directory(p_campaign_id text)
returns table (
  user_id uuid,
  username text,
  role text,
  joined_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    cm.user_id,
    coalesce(nullif(btrim(p.username), ''), 'Unnamed Adventurer') as username,
    cm.role,
    cm.joined_at
  from public.campaign_members cm
  left join public.profiles p
    on p.user_id = cm.user_id
  where cm.campaign_id = p_campaign_id
    and public.is_campaign_member(p_campaign_id)
  order by cm.joined_at asc;
$$;

grant execute on function public.list_campaign_member_directory(text) to authenticated;

alter table public.chat_messages enable row level security;

drop policy if exists chat_messages_member_read on public.chat_messages;
create policy chat_messages_member_read
  on public.chat_messages
  for select
  using (
    public.is_campaign_member(chat_messages.campaign_id)
    and (
      chat_messages.recipient_user_id is null
      or chat_messages.recipient_user_id = auth.uid()
      or chat_messages.author_user_id = auth.uid()
    )
  );

drop policy if exists chat_messages_member_insert on public.chat_messages;
create policy chat_messages_member_insert
  on public.chat_messages
  for insert
  with check (
    author_user_id = auth.uid()
    and public.is_campaign_member(chat_messages.campaign_id)
    and (
      chat_messages.recipient_user_id is null
      or (
        chat_messages.recipient_user_id <> auth.uid()
        and public.is_campaign_member(chat_messages.campaign_id, chat_messages.recipient_user_id)
      )
    )
  );

update public.chat_messages cm
set author_display = p.username
from public.profiles p
where p.user_id = cm.author_user_id
  and nullif(btrim(p.username), '') is not null
  and cm.author_display <> p.username;

do $$
begin
  if not exists (
    select 1
      from pg_publication_tables
     where pubname = 'supabase_realtime'
       and schemaname = 'public'
       and tablename = 'chat_messages'
  ) then
    alter publication supabase_realtime add table public.chat_messages;
  end if;
end;
$$;
