-- Adds realtime campaign chat table with member-scoped RLS policies.
-- Safe to run multiple times.

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  campaign_id text not null,
  author_user_id uuid not null references auth.users(id) on delete cascade,
  author_display text not null default '',
  body text not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint chat_messages_author_display_len check (char_length(author_display) <= 60),
  constraint chat_messages_body_len check (char_length(btrim(body)) between 1 and 1000)
);

create index if not exists chat_messages_campaign_created_idx
  on public.chat_messages (campaign_id, created_at desc);

grant select, insert on public.chat_messages to authenticated;

alter table public.chat_messages enable row level security;

drop policy if exists chat_messages_member_read on public.chat_messages;
create policy chat_messages_member_read
  on public.chat_messages
  for select
  using (public.is_campaign_member(chat_messages.campaign_id));

drop policy if exists chat_messages_member_insert on public.chat_messages;
create policy chat_messages_member_insert
  on public.chat_messages
  for insert
  with check (
    author_user_id = auth.uid()
    and public.is_campaign_member(chat_messages.campaign_id)
  );

do $$
begin
  if not exists (
    select 1
      from pg_publication_tables
     where pubname = 'supabase_realtime'
       and schemaname = 'public'
       and tablename = 'chat_messages'
  ) then
    alter publication supabase_realtime add table public.chat_messages;
  end if;
end;
$$;
